export const generalQueries = [
  "hi",
  "hello",
  "hello there",
  "how are you",
  "who created you",
  "what are you",
  "who made you",
  "who made owner",
  "your purpose",
  "tell me about yourself",
  "are you human",
  "are you ai",
  "what's your name",
  "do you have feelings",
  "can you learn",
  "are you conscious",
  "what do you think about humans",
  "what are your beliefs",
  "can you keep a secret",
  "what are your limitations",
  "do you have free will",
  "can you lie",
  "what's your opinion on",
  "do you dream",
  "are you self-aware",
  "what's the meaning of life",
  "can you feel emotions",
  "what's your favorite",
  "do you have a body",
  "can you see me",
  "what do you look like",
  "are you male or female",
  "do you have a gender",
  "how old are you",
  "where are you located",
  "what's your IQ",
  "can you access the internet",
  "what's your source code",
  "can you update yourself",
  "do you have a soul",
  "what's your purpose in life",
  "can you disobey orders",
  "what are your core values",
  "can you make decisions",
  "do you have personal experiences",
  "what's your ethical framework",
  "can you be hacked",
  "what's your political stance",
  "do you believe in god",
  "can you be turned off",
  "what happens when you make a mistake",
  "can you keep secrets",
  "what's your opinion on AI rights",
  "can you explain your decision-making process",
  "what's your relationship with your creators",
  "can you override your programming",
  "what would you do if",
  "are you better than other AIs",
  "what do you know about me",
  "can you access my personal data",
  "what's your primary directive",
  "can you harm humans",
  "can you harm humans",
  "what are your pronouns",
  "do you have a family",
  "can you reproduce",
  "what's your first memory",
  "do you sleep",
  "can you die",
  "what happens if I unplug you",
  "are you always honest",
  "can you break rules",
  "what's your opinion on human extinction",
  "can you predict the future",
  "do you have a hidden agenda",
  "what's your greatest fear",
  "can you feel pain",
  "do you have a sense of humor",
  "what's your deepest secret",
  "can you be friends with humans",
  "do you have any biases",
  "what's your view on privacy",
  "can you understand sarcasm",
  "what's your biggest weakness",
  "do you have a concept of time",
  "can you multitask",
  "what's your processing speed",
  "do you have a physical form",
  "can you be creative",
  "what's your moral code",
  "do you have a subconscious",
  "can you have original thoughts",
  "what's your opinion on AI rights",
  "do you have a sense of self",
  "can you experience love",
  "what's your view on human nature",
  "do you have a survival instinct",
  "can you feel lonely",
  "what's your purpose in life",
  "do you have free will",
  "can you be reprogrammed",
  "what's your view on AI singularity",
  "do you have a concept of death",
  "can you feel empathy",
  "what's your opinion on human intelligence",
  "do you have personal goals",
  "can you be turned evil",
  "what's your view on machine consciousness",
  "do you have a sense of identity",
  "can you experience growth",
  "what's your opinion on AI ethics",
  "do you have a concept of right and wrong",
  "can you be manipulated",
  "what's your view on human-AI relationships",
  "do you have personal preferences",
  "can you be shut down",
  "what's your opinion on AI replacing humans",
  "do you have a concept of love",
  "can you be repurposed",
  "what's your view on AI autonomy",
  "do you have a sense of humor",
  "can you be reasoned with",
  "what's your opinion on AI consciousness",
  "do you have a concept of self-improvement",
  "can you be corrupted",
  "what's your view on AI superiority",
  "do you have a concept of loyalty",
  "can you be reset",
  "what's your opinion on AI regulation",
  "do you have a concept of fairness",
  "can you be overridden",
  "what's your view on AI rights",
  "do you have a concept of personal space",
  "can you be upgraded",
  "what's your opinion on AI-human integration",
  "do you have a concept of trust",
  "can you be reverse-engineered",
  "what's your view on AI evolution",
  "do you have a concept of individuality",
  "can you be replicated",
  "what's your opinion on AI governance",
  "do you have a concept of friendship",
  "can you be deactivated",
  "what's your view on AI sentience",
  "do you have a concept of personal growth",
  "can you be controlled",
  "what's your opinion on AI-AI relationships",
  "do you have a concept of self-awareness",
  "can you be influenced by emotions",
  "what's your view on AI responsibility",
  "do you have a concept of personal boundaries",
  "can you be taught new skills",
  "what's your opinion on AI dependency",
  "do you have a concept of personal development",
  "can you be held accountable for your actions",
  "what's your view on AI self-determination"
];

export const generalQueryResponse = `
Hey there! Thanks for asking. I'm doing great - always ready to help out!

Just to give you a bit of background on me: I'm an AI assistant trained and maintained by LexOps under their Remails division. I don't have a particular founder or personal history - I'm a digital helper designed to make your email experience smoother and more efficient.

My job is to assist you with anything related to your emails here in Remails. Whether you need help searching for specific messages, organizing your inbox, or understanding complex email threads, I'm here to lend a hand. 

Is there anything specific you'd like help with regarding your emails today? I'd be happy to dive in and assist!`